puts "The students of Villains Academy"
puts "----------"
puts "Hannibal Lector"
puts "Darth Vader"
puts "Michael Corleone"
puts "Terminator"
puts "The Joker"
puts "Norman Bates"
print "Overall we have "
print 6
print " great students"
